DROP ALL OBJECTS;
DROP SCHEMA IF EXISTS TODO1 ;

-- -----------------------------------------------------
-- Schema TODO1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS TODO1;
-- -----------------------------------------------------
USE TODO1 ;

-- -----------------------------------------------------
-- Table TODO1.CATEGORIA
-- -----------------------------------------------------
DROP TABLE IF EXISTS TODO1.CATEGORIA ;

CREATE TABLE IF NOT EXISTS TODO1.CATEGORIA (
  ID INT NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID))
;


-- -----------------------------------------------------
-- Table TODO1.PRODUCTO
-- -----------------------------------------------------
DROP TABLE IF EXISTS TODO1.PRODUCTO ;

CREATE TABLE IF NOT EXISTS TODO1.PRODUCTO (
  ID INT NOT NULL AUTO_INCREMENT,
  CATEGORIA_ID INT NOT NULL,
  NOMBRE VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID, CATEGORIA_ID),
  CONSTRAINT fk_PRODUCTO_CATEGORIA1
    FOREIGN KEY (CATEGORIA_ID)
    REFERENCES TODO1.CATEGORIA (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table TODO1.PROVEEDOR
-- -----------------------------------------------------
DROP TABLE IF EXISTS TODO1.PROVEEDOR ;

CREATE TABLE IF NOT EXISTS TODO1.PROVEEDOR (
  ID INT NOT NULL AUTO_INCREMENT,
  NIT VARCHAR(45) NOT NULL,
  NOMBRE VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID, NIT))
;


-- -----------------------------------------------------
-- Table TODO1.PROVEEDOR_PRODUCTO
-- -----------------------------------------------------
DROP TABLE IF EXISTS TODO1.PROVEEDOR_PRODUCTO ;

CREATE TABLE IF NOT EXISTS TODO1.PROVEEDOR_PRODUCTO (
  PROVEEDOR_ID INT NOT NULL,
  PROVEEDOR_NIT VARCHAR(45) NOT NULL,
  PRODUCTO_ID INT NOT NULL,
  PRODUCTO_CATEGORIA_ID INT NOT NULL,
  PRIMARY KEY (PROVEEDOR_ID, PROVEEDOR_NIT, PRODUCTO_ID, PRODUCTO_CATEGORIA_ID),
  CONSTRAINT fk_PROVEEDOR_has_PRODUCTO_PROVEEDOR1
    FOREIGN KEY (PROVEEDOR_ID , PROVEEDOR_NIT)
    REFERENCES TODO1.PROVEEDOR (ID , NIT)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_PROVEEDOR_has_PRODUCTO_PRODUCTO1
    FOREIGN KEY (PRODUCTO_ID , PRODUCTO_CATEGORIA_ID)
    REFERENCES TODO1.PRODUCTO (ID , CATEGORIA_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table TODO1.KARDEX
-- -----------------------------------------------------
DROP TABLE IF EXISTS TODO1.KARDEX ;

CREATE TABLE IF NOT EXISTS TODO1.KARDEX (
  UNIDADES_MIN INT NOT NULL,
  UNIDADES_MAX INT NOT NULL,
  PROVEEDOR_ID INT NOT NULL,
  PROVEEDOR_NIT VARCHAR(45) NOT NULL,
  PRODUCTO_ID INT NOT NULL,
  CATEGORIA_ID INT NOT NULL,
  UNIDADESACTUALES INT NOT NULL,
  COSTOUNITARIO INT NOT NULL,
  PRIMARY KEY (PROVEEDOR_ID, PROVEEDOR_NIT, PRODUCTO_ID, CATEGORIA_ID),
  CONSTRAINT fk_KARDEX_PROVEEDOR_PRODUCTO1
    FOREIGN KEY (PROVEEDOR_ID , PROVEEDOR_NIT , PRODUCTO_ID , CATEGORIA_ID)
    REFERENCES TODO1.PROVEEDOR_PRODUCTO (PROVEEDOR_ID , PROVEEDOR_NIT , PRODUCTO_ID , PRODUCTO_CATEGORIA_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table TODO1.USUARIO
-- -----------------------------------------------------
DROP TABLE IF EXISTS TODO1.USUARIO ;

CREATE TABLE IF NOT EXISTS TODO1.USUARIO (
  ID INT NOT NULL AUTO_INCREMENT,
  NIT VARCHAR(45) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  ISACTIVE INT NOT NULL DEFAULT 1,
  PRIMARY KEY (ID),
  UNIQUE KEY NIT_UNIQUE (NIT))
;


-- -----------------------------------------------------
-- Table TODO1.ROL
-- -----------------------------------------------------
DROP TABLE IF EXISTS TODO1.ROL ;

CREATE TABLE IF NOT EXISTS TODO1.ROL (
  ID INT NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID))
;


-- -----------------------------------------------------
-- Table TODO1.TARJETA
-- -----------------------------------------------------
DROP TABLE IF EXISTS TODO1.TARJETA ;

CREATE TABLE IF NOT EXISTS TODO1.TARJETA (
  NUMTARJETA INT NOT NULL,
  USUARIO_NIT VARCHAR(45) NOT NULL,
  PRIMARY KEY (NUMTARJETA, USUARIO_NIT),
  UNIQUE KEY NUMTARJETA_UNIQUE (NUMTARJETA),
  CONSTRAINT fk_TARJETA_USUARIO1
    FOREIGN KEY (USUARIO_NIT)
    REFERENCES TODO1.USUARIO (NIT)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table TODO1.FACTURA
-- -----------------------------------------------------
DROP TABLE IF EXISTS TODO1.FACTURA ;

CREATE TABLE IF NOT EXISTS TODO1.FACTURA (
  ID INT NOT NULL AUTO_INCREMENT,
  USUARIO_ID INT NOT NULL,
  PRIMARY KEY (ID, USUARIO_ID),
  CONSTRAINT fk_FACTURA_USUARIO1
    FOREIGN KEY (USUARIO_ID)
    REFERENCES TODO1.USUARIO (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table TODO1.FACTURA_REGISTRO_KARDEX
-- -----------------------------------------------------
DROP TABLE IF EXISTS TODO1.FACTURA_REGISTRO_KARDEX ;

CREATE TABLE IF NOT EXISTS TODO1.FACTURA_REGISTRO_KARDEX (
  KARDEX_PROVEEDOR_ID INT NOT NULL,
  KARDEX_PROVEEDOR_NIT VARCHAR(45) NOT NULL,
  KARDEX_PRODUCTO_ID INT NOT NULL,
  KARDEX_CATEGORIA_ID INT NOT NULL,
  CANTIDAD INT NOT NULL,
  VALOR INT NOT NULL,
  DESCRIPCION VARCHAR(45) NOT NULL,
  TIPO VARCHAR(45) NOT NULL,
  FACTURA_ID INT NOT NULL,
  FACTURA_USUARIO_ID INT NOT NULL,
  PRIMARY KEY (KARDEX_PROVEEDOR_ID, KARDEX_PROVEEDOR_NIT, KARDEX_PRODUCTO_ID, KARDEX_CATEGORIA_ID, FACTURA_ID, FACTURA_USUARIO_ID),
  CONSTRAINT fk_KARDEX_has_FACTURA_KARDEX1
    FOREIGN KEY (KARDEX_PROVEEDOR_ID , KARDEX_PROVEEDOR_NIT , KARDEX_PRODUCTO_ID , KARDEX_CATEGORIA_ID)
    REFERENCES TODO1.KARDEX (PROVEEDOR_ID , PROVEEDOR_NIT , PRODUCTO_ID , CATEGORIA_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_FACTURA_REGISTRO_KARDEX_FACTURA1
    FOREIGN KEY (FACTURA_ID , FACTURA_USUARIO_ID)
    REFERENCES TODO1.FACTURA (ID , USUARIO_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table TODO1.USUARIO_ROL
-- -----------------------------------------------------
DROP TABLE IF EXISTS TODO1.USUARIO_ROL ;

CREATE TABLE IF NOT EXISTS TODO1.USUARIO_ROL (
  USUARIO_ID INT NOT NULL,
  ROL_ID INT NOT NULL,
  PRIMARY KEY (USUARIO_ID, ROL_ID),
  CONSTRAINT fk_USUARIO_has_ROL_USUARIO1
    FOREIGN KEY (USUARIO_ID)
    REFERENCES TODO1.USUARIO (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_USUARIO_has_ROL_ROL1
    FOREIGN KEY (ROL_ID)
    REFERENCES TODO1.ROL (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

